host:
  hostname: cephaio
  ip: 172.16.4.204
network:
  interface: ens160 ens192 
  ens160:
    ip: 172.16.4.204/24
    gateway: 172.16.10.1
    dns: 8.8.8.8
  ens192:
    ip: 10.0.10.1/24
ceph:
  userceph: cephuser
  password: 123456
  disk: /dev/sdb /dev/sdc
  network:
    public: 172.16.4.0/24
    cluster: 10.0.10.0/24
root:
  password: 123456a@